version: '2'
services:

  frontend:
    build: static/.
    ports:
      - "${EXTERNAL_PORT}:3000"
    links:
      - api
    depends_on:
      - api
    image: tferreira/piggydime-frontend

  api:
    build: .
    ports:
      - "${API_PORT}:5000"
    links:
      - mysql
    depends_on:
      - mysql
    image: tferreira/piggydime-api
    args:
      - API_PORT: "${API_PORT}"
    restart: on-failure

  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecure
      MYSQL_DATABASE: piggydime
