version: '2'
services:

  frontend:
    build: static/.
    ports:
      - "80:3000"
    links:
      - api
    depends_on:
      - api

  api:
    build: .
    ports:
      - "5000:5000"
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecure
      MYSQL_DATABASE: piggydime
